version: 2.1

workflows:
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - run:
          name: Install prerequisities
          command: |
            python3 -m pip install pylint
            python3 -m pip install -r requirements.txt
            pyenv rehash

      - run:
          name: Check syntax and style
          command: |
            PYTHON_SCRIPTS=$(grep -l '#!/usr/bin/env python' ssm-* ecs-*)
            pylint --exit-zero --disable=invalid-name,missing-docstring,line-too-long ${PYTHON_SCRIPTS} ssm_tools/*.py
            pylint --errors-only ${PYTHON_SCRIPTS} ssm_tools/*.py


  publish:
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - run:
          name: Verify git tag vs. version
          command: |
            python3 setup.py verify

      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Build packages
          command: ./build.sh

      - run:
          name: Install twine
          command: |
            python3 -m pip install twine
            pyenv rehash

      - run:
          name: Upload to PyPI
          command: |
            twine upload dist/*
